# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: GOXR3PLUSTUDIO
open_collective: # Replace with a single Open Collective username
ko_fi: goxr3plusstudio
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://www.paypal.me/GOXR3PLUSCOMPANY
